name: GitHub Actions Demo
on: [push]
jobs:
  Run-All-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Tox
        run: |
          python3 -m pip install --upgrade pip
          pip3 install tox
      - name: Run Tox
        run: |
          tox
